# Site settings
title: The William Anderson's Blog
email: thewilliamanderson@gmail.com
description: "More Coming soon?"
baseurl: ""
url: "http://thewilliamanderons.com"
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
markdown_ext: md
permalink: pretty
