# Site settings
title: The William Anderson's Blog
email: your-email@domain.com
description: "More COming soon?"
baseurl: ""
url: "http://yourdomain.com"
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
markdown_ext: md
permalink: pretty
